import { Theme } from '@mui/material';

export const styles = {
  imageMockWrapper: (theme: Theme) => ({
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    overflow: 'hidden',
    borderRadius: '10px',
    backgroundColor: theme.palette.action.disabledBackground,
    background: `linear-gradient(
      100deg,
      rgba(255, 255, 255, 0) 40%,
      ${theme.palette.common.surface['surface 44']} 50%,
      rgba(255, 255, 255, 0) 60%
    ) ${theme.palette.action.disabledBackground}`,
    backgroundSize: '200% 100%',
    backgroundPositionX: '180%',
  }),
  deletedImage: {
    width: '100%',
    padding: '10px',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '20px',
  },
  imageErrorWrapper: (theme: Theme) => ({
    width: '100%',
    height: '100%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    overflow: 'hidden',
    borderRadius: '10px',
    backgroundColor: theme.palette.action.disabledBackground,
    '& > div': {
      transform: 'translate(-50%, -50%)',
      width: '100%',
      position: 'absolute',
      top: '50%',
      left: '50%',
      display: 'flex',
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      gap: '20px',
      '@media (min-width: 1500px) and (max-width: 1700px)': {
        gap: '5px',
      },
    },
  }),
  loaded: (theme: Theme, ratio: number) => ({
    width: '100%',
    cursor: 'pointer',
    paddingBottom: `${ratio}%`,
    display: 'flex',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '10px',
    '& img': {
      transition: 'all 0.3s ease-in-out',
    },
    [theme.breakpoints.up('lg')]: {
      '&:hover': {
        '& img': {
          transform: 'scale(1.1)',
        },
        '& div:first-of-type': {
          opacity: 0.4,
        },
        '& div:last-of-type': {
          opacity: 1,
        },
      },
    },
  }),
  loading: (ratio: number) => ({
    width: '100%',
    paddingBottom: `${ratio}%`,
    display: 'flex',
    position: 'relative',
    overflow: 'hidden',
    borderRadius: '10px',
  }),
  imageOverlay: (theme: Theme) => ({
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    background: theme.palette.common.black,
    borderRadius: '10px',
    opacity: 0,
    transition: 'all 0.3s ease-in-out',
    pointerEvents: 'none',
  }),
  eye: {
    opacity: 0,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%,-50%)',
    transition: 'all 0.3s ease-in-out',
    pointerEvents: 'none',
  },
  imageWrapper: {
    width: '100%',
    height: '100%',
    position: 'absolute',
    top: 0,
    left: 0,
  },
  loader: {
    position: 'absolute',
    flexDirection: 'column',
    justifyContent: 'space-between',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    display: 'flex',
    padding: '20px',
  },
};
